[project]
name = "mantid-total-scattering-python-wrapper"
dynamic = ["version"]
description = "Mantid Total Scattering Reduction"
readme = "README.md"
license = { text = "GPL-3.0-only" }
authors = [
  { name = "Yuanpeng Zhang", email = "zhangy3@ornl.gov" },
  { name = "Marshall McDonnell", email = "mcondonnellmd@ornl.gov" },
  { name = "Peter Peterson" },
  { name = "Coleman Kendrick" },
  { name = "Jenna DeLozier" },
  { name = "Elliot Oram" },
  { name = "Donnie Earnest" },
]
dependencies = [
  "matplotlib",
  "pyoncat @ https://oncat.ornl.gov/packages/pyoncat-1.5.1-py3-none-any.whl",
  "scikit-learn",
]

[project.scripts]
mantidtotalscattering = "total_scattering.cli:main"

[project.urls]
Homepage = "https://github.com/neutrons/mantid_total_scattering"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "versioningit"]

[tool.hatch.version]
source = "versioningit"

[tool.hatch.build.hooks.versioningit-onbuild]
source-file = "total_scattering/_version.py"
build-file = "total_scattering/_version.py"


[tool.hatch.build]
artifacts = [
  "total_scattering/_version.py",
  "total_scattering/**/*.yml",
  "total_scattering/**/*.yaml",
  "total_scattering/**/*.ini",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["total_scattering"]

[tool.versioningit.vcs]
method = "git"
default-tag = "0.1.0"

[tool.versioningit.next-version]
method = "minor"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}"
# Since pixi builds currently require the package version to be set statically in pyproject.toml,
# and we solve that by temporarily changing pyproject.toml during build using the pixi tasks
# sync-version and reset-toml, then we need to ignore uncommitted changes in order for the wheel
# version to be consistent with the package version
dirty = "{version}"
distance-dirty = "{next_version}.dev{distance}"

[tool.versioningit.write]
file = "total_scattering/_version.py"

[tool.pixi.workspace]
preview = ["pixi-build"]
channels = ["conda-forge", "https://prefix.dev/pixi-build-backends"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = "*"
pip = "*"
matplotlib = "*"

[tool.pixi.pypi-dependencies]
# PyPI dependencies, including this package to allow local editable installs
total_scattering = { path = ".", editable = true }


[tool.pixi.package.host-dependencies]
hatchling = "*"
versioningit = "*"

[tool.pixi.feature.package.pypi-dependencies]
toml-cli = "*"

[tool.pixi.package.run-dependencies]
python = ">=3.10"
matplotlib = "*"
scikit-learn = "*"


# ------------------------------- #
# Pixi Feature Dependencies       #
# ------------------------------- #

# FEATURE DEFINITION ORDER MATTERS FOR CHANNEL DECLARATION
[tool.pixi.feature.package-wrapper]
channels = ["conda-forge", "https://prefix.dev/pixi-build-backends"]
dependencies = { python = "*", pip = "*", matplotlib = "*", scikit-learn = "*", toml = "*", hatchling = "*", versioningit = "*" }


[tool.pixi.package]
name = "mantid-total-scattering-python-wrapper"
version = "0.0.0"                               # placeholder, overwritten by sync-version

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "0.4.*", channels = [
  "conda-forge",
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
] }


[tool.pixi.environments]
package-wrapper = { features = ["package-wrapper"], solve-group = "wrapper" }

# --------------- #
# Pixi Tasks      #
# --------------- #
[tool.pixi.tasks]
# MISC
sync-version = { cmd = 'version=$(python -m versioningit); toml set tool.pixi.package.version "$version" --toml-path pyproject.toml', description = "Sync pyproject.toml version with Git version" }
[tool.pixi.feature.package-wrapper.tasks]
prep-channels = { cmd = "pixi workspace channel list", description = "Prepare the conda channels for the package" }
backup-toml = { cmd = "cp pyproject.toml pyproject.toml.bak", description = "Backup the pyproject.toml file" }
reset-toml = { cmd = "cp pyproject.toml.bak pyproject.toml; rm pyproject.toml.bak", description = "Reset the pyproject.toml file to the original state" }
build-conda-command-wrapper = { cmd = "pixi build", description = "Build the conda package command" }
build-conda-wrapper = { description = "Build the conda package", depends-on = [
  "prep-channels",
  "backup-toml",
  "sync-version",
  "build-conda-command-wrapper",
  "reset-toml",
] }
