{% set data = load_setup_py_data() %}

package:
  name: "mantid-total-scattering"
  version: "{{ data['version'] }}"

source:
  path: ../..

build:
  string: py{{py}}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - mantidworkbench>6.6
    - python
    - setuptools
    - matplotlib
    - scikit-learn

  run:
    - {{ pin_compatible("mantidworkbench", max_pin="x.x") }}
    - python
    - matplotlib
    - scikit-learn

test:
  imports:
    - total_scattering
    - total_scattering.file_handling
    - total_scattering.file_handling.load
    - total_scattering.file_handling.save
    - total_scattering.inelastic
    - total_scattering.inelastic.placzek
    - total_scattering.reduction
    - total_scattering.reduction.total_scattering_reduction

about:
  home: https://github.com/neutrons/mantid_total_scattering
  license: GPL (version 3)
  license_family: GPL3
  license_file: 
  summary: Mantid Total Scattering Reduction

extra:
  recipe-maintainers:
    - Kvieta1990
