name: mantid_total_scattering_ci

env:
  PYTHON_MAIN_VERSION: 3.11

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next]
    tags: ['v*']

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for versioneer

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.12
        with:
          pixi-version: v0.49.0

      - name: Install dependencies and setup environment
        run: |
          pixi install
          sudo apt-get install libglu1-mesa

      - name: Lint with pixi
        if: ${{ matrix.python-version == env.PYTHON_MAIN_VERSION }}
        run: |
          pixi run lint
          pixi run bandit total_scattering  # Security linting

      - name: Test with pixi
        run: |
          pixi run test-pytest

      - name: Coverage - create and upload report
        if: ${{ matrix.python-version == env.PYTHON_MAIN_VERSION }}
        run: |
          pixi run pytest --cov=total_scattering --cov-report=xml
        
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == env.PYTHON_MAIN_VERSION }}
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Build conda package
        run: |
          cd conda.recipe/mantid-total-scattering
          pixi run -e build conda mambabuild --output-folder . -c neutrons -c oncat .

      - name: Deploy full package to Anaconda
        if: startsWith( github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          cd conda.recipe/mantid-total-scattering
          pixi run anaconda upload --label $CONDA_LABEL linux-64/*.tar.bz2

      - name: Deploy python wrapper to Anaconda
        if: startsWith( github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          cd conda.recipe/mantid-total-scattering-python-wrapper
          pixi run -e build conda build --output-folder . .
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          pixi run anaconda upload --label $CONDA_LABEL noarch/*.tar.bz2

  trigger-deploy:
    runs-on: ubuntu-22.04
    needs: [linux]
    # only trigger deploys from protected branches and tags
    # if: ${{ github.ref_protected || github.ref_type == 'tag' }}
    if: false
    steps:
      - name: Determine Environment
        uses: neutrons/branch-mapper@v2
        id: conda_env_name
        with:
          prefix: mantidtotalscattering

      - name: Trigger deploy
        id: trigger
        uses: eic/trigger-gitlab-ci@v2
        with:
          url: https://code.ornl.gov
          token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          project_id: 7835
          ref_name: main
          variables: |
            PLAY="update"
            CONDA_ENV="${{ steps.conda_env_name.outputs.name }}"

      - name: Annotate commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            GitLab pipeline for ${{ steps.conda_env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}